"""init

Revision ID: 14b5e5a4c0b5
Revises: None
Create Date: 2014-07-31 10:14:37.843000

"""

# revision identifiers, used by Alembic.
revision = '14b5e5a4c0b5'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_academy',
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_academy')),
    sa.UniqueConstraint('name', name=op.f('uq__xiaoyuan_academy__name'))
    )
    op.create_table('xiaoyuan_academies_users',
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['xiaoyuan_academy.id'], name=op.f('fk__xiaoyuan_academies_users__academy_id__xiaoyuan_academy')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_academies_users__user_id__security_user'))
    )
    op.create_table('xiaoyuan_message',
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_message__sender_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_message'))
    )
    op.create_table('xiaoyuan_class',
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['xiaoyuan_academy.id'], name=op.f('fk__xiaoyuan_class__academy_id__xiaoyuan_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_class')),
    sa.UniqueConstraint('name', name=op.f('uq__xiaoyuan_class__name'))
    )
    op.create_table('xiaoyuan_messages_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(name='is_read'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['xiaoyuan_message.id'], name=op.f('fk__xiaoyuan_messages_users__message_id__xiaoyuan_message')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_messages_users__user_id__security_user')),
    sa.PrimaryKeyConstraint('user_id', 'message_id', name=op.f('pk__xiaoyuan_messages_users'))
    )
    op.create_table('xiaoyuan_academies_classes',
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['xiaoyuan_academy.id'], name=op.f('fk__xiaoyuan_academies_classes__academy_id__xiaoyuan_academy')),
    sa.ForeignKeyConstraint(['class_id'], ['xiaoyuan_class.id'], name=op.f('fk__xiaoyuan_academies_classes__class_id__xiaoyuan_class'))
    )
    op.create_table('xiaoyuan_classes_users',
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['xiaoyuan_class.id'], name=op.f('fk__xiaoyuan_classes_users__class_id__xiaoyuan_class')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_classes_users__user_id__security_user'))
    )
    op.alter_column(u'carpool_carpoolinfo', 'delete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='deleted'),
               existing_nullable=False)
    op.alter_column(u'job_job', 'delete',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='deleted'),
               existing_nullable=False)
    op.alter_column(u'job_report', 'is_audit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_audit'),
               existing_nullable=True)
    op.alter_column(u'qingbank_doc', 'is_leaf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_leaf'),
               existing_nullable=True)
    op.alter_column(u'security_user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='active'),
               existing_nullable=True)
    op.alter_column(u'security_user', 'bind_remind',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='bind_remind'),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'security_user', 'bind_remind',
               existing_type=sa.Boolean(name='bind_remind'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'security_user', 'active',
               existing_type=sa.Boolean(name='active'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'qingbank_doc', 'is_leaf',
               existing_type=sa.Boolean(name='is_leaf'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'job_report', 'is_audit',
               existing_type=sa.Boolean(name='is_audit'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column(u'job_job', 'delete',
               existing_type=sa.Boolean(name='deleted'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column(u'carpool_carpoolinfo', 'delete',
               existing_type=sa.Boolean(name='deleted'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_table('xiaoyuan_classes_users')
    op.drop_table('xiaoyuan_academies_classes')
    op.drop_table('xiaoyuan_messages_users')
    op.drop_table('xiaoyuan_class')
    op.drop_table('xiaoyuan_message')
    op.drop_table('xiaoyuan_academies_users')
    op.drop_table('xiaoyuan_academy')
    ### end Alembic commands ###
