"""add reply_message

Revision ID: 2c71a58d30a3
Revises: 14b5e5a4c0b5
Create Date: 2014-07-31 15:52:18.383000

"""

# revision identifiers, used by Alembic.
revision = '2c71a58d30a3'
down_revision = '14b5e5a4c0b5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk__xiaoyuan_academies_classes__academy_id__xiaoyuan_academy', table_name='xiaoyuan_academies_classes')
    op.drop_index('fk__xiaoyuan_academies_classes__class_id__xiaoyuan_class', table_name='xiaoyuan_academies_classes')
    op.drop_index('fk__xiaoyuan_academies_users__academy_id__xiaoyuan_academy', table_name='xiaoyuan_academies_users')
    op.drop_index('fk__xiaoyuan_academies_users__user_id__security_user', table_name='xiaoyuan_academies_users')
    op.drop_index('fk__xiaoyuan_class__academy_id__xiaoyuan_academy', table_name='xiaoyuan_class')
    op.drop_index('fk__xiaoyuan_classes_users__class_id__xiaoyuan_class', table_name='xiaoyuan_classes_users')
    op.drop_index('fk__xiaoyuan_classes_users__user_id__security_user', table_name='xiaoyuan_classes_users')
    op.add_column('xiaoyuan_message', sa.Column('reply_message_id', sa.Integer(), nullable=True))
    op.drop_index('fk__xiaoyuan_message__sender_id__security_user', table_name='xiaoyuan_message')
    op.drop_index('fk__xiaoyuan_messages_users__message_id__xiaoyuan_message', table_name='xiaoyuan_messages_users')
    ### end Alembic commands ###
def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fk__xiaoyuan_messages_users__message_id__xiaoyuan_message', 'xiaoyuan_messages_users', ['message_id'], unique=False)
    op.create_index('fk__xiaoyuan_message__sender_id__security_user', 'xiaoyuan_message', ['sender_id'], unique=False)
    op.drop_column('xiaoyuan_message', 'reply_message_id')
    op.create_index('fk__xiaoyuan_classes_users__user_id__security_user', 'xiaoyuan_classes_users', ['user_id'], unique=False)
    op.create_index('fk__xiaoyuan_classes_users__class_id__xiaoyuan_class', 'xiaoyuan_classes_users', ['class_id'], unique=False)
    op.create_index('fk__xiaoyuan_class__academy_id__xiaoyuan_academy', 'xiaoyuan_class', ['academy_id'], unique=False)
    op.create_index('fk__xiaoyuan_academies_users__user_id__security_user', 'xiaoyuan_academies_users', ['user_id'], unique=False)
    op.create_index('fk__xiaoyuan_academies_users__academy_id__xiaoyuan_academy', 'xiaoyuan_academies_users', ['academy_id'], unique=False)
    op.create_index('fk__xiaoyuan_academies_classes__class_id__xiaoyuan_class', 'xiaoyuan_academies_classes', ['class_id'], unique=False)
    op.create_index('fk__xiaoyuan_academies_classes__academy_id__xiaoyuan_academy', 'xiaoyuan_academies_classes', ['academy_id'], unique=False)
    ### end Alembic commands ###
