"""add profile

Revision ID: 2deb650e1183
Revises: 509561b230f6
Create Date: 2014-12-28 13:05:35.815000

"""

# revision identifiers, used by Alembic.
revision = '2deb650e1183'
down_revision = '509561b230f6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_profile',
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('truename', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('college', sa.String(length=30), nullable=True),
    sa.Column('in_college_date', sa.Date(), nullable=True),
    sa.Column('major', sa.String(length=30), nullable=True),
    sa.Column('clazz', sa.String(length=30), nullable=True),
    sa.Column('hobby', sa.String(length=100), nullable=True),
    sa.Column('special', sa.String(length=100), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    sa.Column('version', sa.Integer(), nullable=False),    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__security_profile__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__security_profile')),
    sa.UniqueConstraint('nickname', name=op.f('uq__security_profile__nickname'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_profile')
    ### end Alembic commands ###
