"""create job

Revision ID: 300128dde62b
Revises: 271a9948c694
Create Date: 2014-06-27 17:24:07.823000

"""

# revision identifiers, used by Alembic.
revision = '300128dde62b'
down_revision = '271a9948c694'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('content', sa.String(length=5120), nullable=True),
    sa.Column('job_type', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__job_job__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__job_job'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_job')
    ### end Alembic commands ###
