"""Add user bind_remind

Revision ID: 38996390258c
Revises: 4d5a96a180f2
Create Date: 2014-06-18 16:47:58.551000

"""

# revision identifiers, used by Alembic.
revision = '38996390258c'
down_revision = '4d5a96a180f2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qingbank_doc', 'is_leaf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_leaf'),
               existing_nullable=True)
    op.add_column('security_user', sa.Column('bind_remind', sa.Boolean(name='bind_remind'), nullable=True))
    op.alter_column('security_user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='active'),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_user', 'active',
               existing_type=sa.Boolean(name='active'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('security_user', 'bind_remind')
    op.alter_column('qingbank_doc', 'is_leaf',
               existing_type=sa.Boolean(name='is_leaf'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
