"""change message way

Revision ID: 38c269d1070c
Revises: 3b2e937e56a1
Create Date: 2014-07-19 01:41:43.110000

"""

# revision identifiers, used by Alembic.
revision = '38c269d1070c'
down_revision = '3b2e937e56a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_msges_users',
    sa.Column('messsage_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['messsage_id'], ['xiaoyuan_message.id'], name=op.f('fk__xiaoyuan_msges_users__messsage_id__xiaoyuan_message')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_msges_users__user_id__security_user'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiaoyuan_msges_users')
    ### end Alembic commands ###
