"""create xiaoyuan

Revision ID: 3b2e937e56a1
Revises: 250adabad5d7
Create Date: 2014-07-11 22:35:40.282000

"""

# revision identifiers, used by Alembic.
revision = '3b2e937e56a1'
down_revision = '250adabad5d7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_academy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_academy')),
    sa.UniqueConstraint('name', name=op.f('uq__xiaoyuan_academy__name'))
    )
    op.create_table('xiaoyuan_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    
    sa.ForeignKeyConstraint(['receiver_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_message__receiver_id__security_user')),
    sa.ForeignKeyConstraint(['sender_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_message__sender_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_message'))
    )
    op.create_table('xiaoyuan_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('academy_id', sa.Integer(), nullable=True),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    
    sa.ForeignKeyConstraint(['academy_id'], ['xiaoyuan_academy.id'], name=op.f('fk__xiaoyuan_class__academy_id__xiaoyuan_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_class')),
    sa.UniqueConstraint('name', name=op.f('uq__xiaoyuan_class__name'))
    )
    op.create_table('xiaoyuan_academies_users',
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['xiaoyuan_academy.id'], name=op.f('fk__xiaoyuan_academies_users__academy_id__xiaoyuan_academy')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_academies_users__user_id__security_user'))
    )
    op.create_table('xiaoyuan_academies_classes',
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['xiaoyuan_academy.id'], name=op.f('fk__xiaoyuan_academies_classes__academy_id__xiaoyuan_academy')),
    sa.ForeignKeyConstraint(['class_id'], ['xiaoyuan_class.id'], name=op.f('fk__xiaoyuan_academies_classes__class_id__xiaoyuan_class'))
    )
    op.create_table('xiaoyuan_classes_users',
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['xiaoyuan_class.id'], name=op.f('fk__xiaoyuan_classes_users__class_id__xiaoyuan_class')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_classes_users__user_id__security_user'))
    )

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiaoyuan_classes_users')
    op.drop_table('xiaoyuan_academies_classes')
    op.drop_table('xiaoyuan_academies_users')
    op.drop_table('xiaoyuan_class')
    op.drop_table('xiaoyuan_message')
    op.drop_table('xiaoyuan_academy')
    ### end Alembic commands ###
