"""app_version

Revision ID: 3b869e1a4a7a
Revises: 4b3d59c759a3
Create Date: 2015-06-26 17:17:48.736000

"""

# revision identifiers, used by Alembic.
revision = '3b869e1a4a7a'
down_revision = '4b3d59c759a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_app', sa.Column('app_version', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_app', 'app_version')
    ### end Alembic commands ###
