"""empty message

Revision ID: 485e1c8d5dd8
Revises: None
Create Date: 2014-04-30 17:31:04.340000

"""

# revision identifiers, used by Alembic.
revision = '485e1c8d5dd8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qingbank_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_leaf', sa.Boolean(name='is_leaf'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['qingbank_doc.id'], name=op.f('fk__qingbank_doc__parent_id__qingbank_doc')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__qingbank_doc'))
    )
    op.create_table('security_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(name='active'), nullable=True),
    sa.Column('nickname', sa.String(length=80), nullable=True),
    sa.Column('bind_username', sa.String(length=255), nullable=True),
    sa.Column('bind_email', sa.String(length=80), nullable=True),
    sa.Column('openid', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=80), nullable=True),
    sa.Column('current_login_ip', sa.String(length=80), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__security_user')),
    sa.UniqueConstraint('email', name=op.f('uq__security_user__email')),
    sa.UniqueConstraint('openid', 'provider', name='uq__user__openid__provider'),
    sa.UniqueConstraint('username', name=op.f('uq__security_user__username'))
    )
    op.create_table('qingbank_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__qingbank_department')),
    sa.UniqueConstraint('name', name=op.f('uq__qingbank_department__name'))
    )
    op.create_table('security_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__security_role')),
    sa.UniqueConstraint('name', name=op.f('uq__security_role__name'))
    )
    op.create_table('qingbank_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('name_pinyin', sa.String(length=30), nullable=True),
    sa.Column('name_shot', sa.String(length=10), nullable=True),
    sa.Column('duty', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=14), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('innerphone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=14), nullable=True),
    sa.Column('qq', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['qingbank_department.id'], name=op.f('fk__qingbank_contact__department_id__qingbank_department')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__qingbank_contact__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__qingbank_contact'))
    )
    op.create_table('security_roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['security_role.id'], name=op.f('fk__security_roles_users__role_id__security_role')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__security_roles_users__user_id__security_user'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_roles_users')
    op.drop_table('qingbank_contact')
    op.drop_table('security_role')
    op.drop_table('qingbank_department')
    op.drop_table('security_user')
    op.drop_table('qingbank_doc')
    ### end Alembic commands ###
