"""update_url

Revision ID: e65ce663116
Revises: 288905881647
Create Date: 2015-06-29 09:47:55.917000

"""

# revision identifiers, used by Alembic.
revision = 'e65ce663116'
down_revision = '288905881647'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_app', sa.Column('update_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_app', 'update_url')
    ### end Alembic commands ###
