"""add wish

Revision ID: 115d6a8e988c
Revises: 5a84debe0627
Create Date: 2015-10-26 17:29:30.001000

"""

# revision identifiers, used by Alembic.
revision = '115d6a8e988c'
down_revision = '5a84debe0627'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish_wish',
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__wish_wish'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ##
    op.drop_table('wish_wish')
    ### end Alembic commands ###
