"""restruct table

Revision ID: 1fc9c81d2b21
Revises: 115d6a8e988c
Create Date: 2015-11-27 15:51:36.053000

"""

# revision identifiers, used by Alembic.
revision = '1fc9c81d2b21'
down_revision = '115d6a8e988c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carpool_carpoolinfo', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='deleted'),
               existing_nullable=False)
    op.drop_index('fk__carpool_carpoolinfo__user_id__security_user', table_name='carpool_carpoolinfo')
    op.alter_column('job_job', 'deleted',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='deleted'),
               existing_nullable=False)
    op.drop_index('fk__job_job__user_id__security_user', table_name='job_job')
    op.alter_column('job_report', 'is_audit',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_audit'),
               existing_nullable=True)
    op.drop_index('fk__job_report__job_id__job_job', table_name='job_report')
    op.alter_column('qingbank_doc', 'is_leaf',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_leaf'),
               existing_nullable=True)
    op.drop_index('fk__security_roles_rights__right_id__security_right', table_name='security_roles_rights')
    op.drop_index('fk__security_roles_rights__role_id__security_role', table_name='security_roles_rights')
    op.alter_column('security_sysmessage', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_read'),
               existing_nullable=False)
    op.alter_column('security_user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='active'),
               existing_nullable=True)
    op.alter_column('security_user', 'bind_remind',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='bind_remind'),
               existing_nullable=True)
    op.drop_index('fk__security_users_apps__app_id__security_app', table_name='security_users_apps')
    op.drop_index('fk__security_users_apps__user_id__security_user', table_name='security_users_apps')
    op.drop_index('fk__security_users_rights__right_id__security_right', table_name='security_users_rights')
    op.drop_index('fk__security_users_rights__user_id__security_user', table_name='security_users_rights')
    op.drop_index('fk__security_users_roles__role_id__security_role', table_name='security_users_roles')
    op.drop_index('fk__security_users_roles__user_id__security_user', table_name='security_users_roles')
    op.alter_column('xiaoyuan_class_user', 'is_charger',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_charger'),
               existing_nullable=True)
    op.alter_column('xiaoyuan_messages_users', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(name='is_read'),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq__xiaoyuan_profile__nickname'), 'xiaoyuan_profile', ['nickname'])
    op.drop_index('uq__security_profile__nickname', table_name='xiaoyuan_profile')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq__security_profile__nickname', 'xiaoyuan_profile', ['nickname'], unique=True)
    op.drop_constraint(op.f('uq__xiaoyuan_profile__nickname'), 'xiaoyuan_profile', type_='unique')
    op.alter_column('xiaoyuan_messages_users', 'is_read',
               existing_type=sa.Boolean(name='is_read'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('xiaoyuan_class_user', 'is_charger',
               existing_type=sa.Boolean(name='is_charger'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.create_index('fk__security_users_roles__user_id__security_user', 'security_users_roles', ['user_id'], unique=False)
    op.create_index('fk__security_users_roles__role_id__security_role', 'security_users_roles', ['role_id'], unique=False)
    op.create_index('fk__security_users_rights__user_id__security_user', 'security_users_rights', ['user_id'], unique=False)
    op.create_index('fk__security_users_rights__right_id__security_right', 'security_users_rights', ['right_id'], unique=False)
    op.create_index('fk__security_users_apps__user_id__security_user', 'security_users_apps', ['user_id'], unique=False)
    op.create_index('fk__security_users_apps__app_id__security_app', 'security_users_apps', ['app_id'], unique=False)
    op.alter_column('security_user', 'bind_remind',
               existing_type=sa.Boolean(name='bind_remind'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('security_user', 'active',
               existing_type=sa.Boolean(name='active'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('security_sysmessage', 'is_read',
               existing_type=sa.Boolean(name='is_read'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.create_index('fk__security_roles_rights__role_id__security_role', 'security_roles_rights', ['role_id'], unique=False)
    op.create_index('fk__security_roles_rights__right_id__security_right', 'security_roles_rights', ['right_id'], unique=False)
    op.alter_column('qingbank_doc', 'is_leaf',
               existing_type=sa.Boolean(name='is_leaf'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.create_index('fk__job_report__job_id__job_job', 'job_report', ['job_id'], unique=False)
    op.alter_column('job_report', 'is_audit',
               existing_type=sa.Boolean(name='is_audit'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.create_index('fk__job_job__user_id__security_user', 'job_job', ['user_id'], unique=False)
    op.alter_column('job_job', 'deleted',
               existing_type=sa.Boolean(name='deleted'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.create_index('fk__carpool_carpoolinfo__user_id__security_user', 'carpool_carpoolinfo', ['user_id'], unique=False)
    op.alter_column('carpool_carpoolinfo', 'deleted',
               existing_type=sa.Boolean(name='deleted'),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    ### end Alembic commands ###
