"""add join_class 

Revision ID: 2679e46a4e27
Revises: 1d7a27a6f75
Create Date: 2014-12-08 15:35:24.257000

"""

# revision identifiers, used by Alembic.
revision = '2679e46a4e27'
down_revision = '1d7a27a6f75'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_joinapply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['xiaoyuan_class.id'], name=op.f('fk__xiaoyuan_joinapply__class_id__xiaoyuan_class')),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_joinapply__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_joinapply'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiaoyuan_joinapply')
    ### end Alembic commands ###
