"""delete memberinfo

Revision ID: 283230e26e5e
Revises: 3933c26bd40b
Create Date: 2015-01-06 12:56:49.266000

"""

# revision identifiers, used by Alembic.
revision = '283230e26e5e'
down_revision = '3933c26bd40b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiaoyuan_classes_users')
    op.drop_table('xiaoyuan_memberinfo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_memberinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('student_no', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('idcard', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_at', mysql.DATETIME(), nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'security_user.id'], name=u'fk__xiaoyuan_memberinfo__user_id__security_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('xiaoyuan_classes_users',
    sa.Column('class_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], [u'xiaoyuan_class.id'], name=u'fk__xiaoyuan_classes_users__class_id__xiaoyuan_class'),
    sa.ForeignKeyConstraint(['user_id'], [u'security_user.id'], name=u'fk__xiaoyuan_classes_users__user_id__security_user'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
