"""app_vercode

Revision ID: 288905881647
Revises: 3b869e1a4a7a
Create Date: 2015-06-29 09:40:19.221000

"""

# revision identifiers, used by Alembic.
revision = '288905881647'
down_revision = '3b869e1a4a7a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_app', sa.Column('app_vercode', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_app', 'app_vercode')
    ### end Alembic commands ###
