"""add tasted

Revision ID: 28ab4d3af2bd
Revises: 5acccc1ff3fe
Create Date: 2016-06-08 15:31:35.593000

"""

# revision identifiers, used by Alembic.
revision = '28ab4d3af2bd'
down_revision = '5acccc1ff3fe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taste_shop',
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__taste_shop__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__taste_shop'))
    )
    op.create_table('taste_item',
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], [u'taste_shop.id'], name=op.f('fk__taste_item__shop_id__taste_shop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__taste_item'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taste_item')
    op.drop_table('taste_shop')
    ### end Alembic commands ###
