"""modify profile

Revision ID: 3e9b1a34ae5a
Revises: 115d6a8e988c
Create Date: 2015-12-13 17:26:14.344000

"""

# revision identifiers, used by Alembic.
revision = '3e9b1a34ae5a'
down_revision = '115d6a8e988c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('truename', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('college', sa.String(length=30), nullable=True),
    sa.Column('in_college_date', sa.Date(), nullable=True),
    sa.Column('major', sa.String(length=30), nullable=True),
    sa.Column('clazz', sa.String(length=30), nullable=True),
    sa.Column('hobby', sa.String(length=100), nullable=True),
    sa.Column('special', sa.String(length=100), nullable=True),
    sa.Column('hometown', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_profile__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_profile')),
    sa.UniqueConstraint('nickname', name=op.f('uq__xiaoyuan_profile__nickname'))
    )
    op.drop_table('security_profile')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_profile',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('truename', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('college', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('in_college_date', sa.DATE(), nullable=True),
    sa.Column('major', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('clazz', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('hobby', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('special', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hometown', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_at', mysql.DATETIME(), nullable=True),
    sa.Column('create_at', mysql.DATETIME(), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'security_user.id'], name=u'security_profile_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('xiaoyuan_profile')
    ### end Alembic commands ###
