"""add is_read

Revision ID: 4b3d59c759a3
Revises: 283230e26e5e
Create Date: 2015-04-27 09:34:22.120000

"""

# revision identifiers, used by Alembic.
revision = '4b3d59c759a3'
down_revision = '283230e26e5e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_sysmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('is_read', sa.Boolean(name='is_read'), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    sa.Column('version', sa.Integer(), nullable=False),    
    sa.ForeignKeyConstraint(['receiver_id'], ['security_user.id'], name=op.f('fk__security_sysmessage__receiver_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__security_sysmessage'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_sysmessage')
    ### end Alembic commands ###
