"""add member

Revision ID: 4b914d2ce17a
Revises: 2679e46a4e27
Create Date: 2014-12-08 23:04:03.276000

"""

# revision identifiers, used by Alembic.
revision = '4b914d2ce17a'
down_revision = '2679e46a4e27'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoyuan_memberinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('student_no', sa.String(length=15), nullable=True),
    sa.Column('idcard', sa.String(length=18), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),    sa.Column('update_at', sa.DateTime(), nullable=True),    sa.Column('create_at', sa.DateTime(), nullable=True),    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['security_user.id'], name=op.f('fk__xiaoyuan_memberinfo__user_id__security_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__xiaoyuan_memberinfo'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xiaoyuan_memberinfo')
    ### end Alembic commands ###
