""" add title for notice

Revision ID: 509561b230f6
Revises: 8fcc4d5b96b
Create Date: 2014-12-25 15:35:15.959000

"""

# revision identifiers, used by Alembic.
revision = '509561b230f6'
down_revision = '8fcc4d5b96b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xiaoyuan_notice', sa.Column('title', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xiaoyuan_notice', 'title')
    ### end Alembic commands ###
