"""add category

Revision ID: 5a84debe0627
Revises: e65ce663116
Create Date: 2015-09-25 15:15:09.095000

"""

# revision identifiers, used by Alembic.
revision = '5a84debe0627'
down_revision = 'e65ce663116'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_category.id'], name=op.f('fk__blog_category__parent_id__blog_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__blog_category'))
    )
    op.add_column(u'blog_blog', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__blog_blog__category_id__blog_category'), 'blog_blog', 'blog_category', ['category_id'], ['id'])
    op.drop_column(u'blog_blog', 'category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'blog_blog', sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk__blog_blog__category_id__blog_category'), 'blog_blog', type_='foreignkey')
    op.drop_column(u'blog_blog', 'category_id')
    op.drop_table('blog_category')
    ### end Alembic commands ###
